config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  get 'reviews/create'
  root "restaurants#index"
  resources :restaurants, only: [:new, :create, :show, :index] do
    resources :reviews, only: [:new, :create]
  end

  #get 'restaurants/new'
  #get 'restaurants/create'
  get 'restaurants/show'
  #get 'restaurants/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, :phone_number, :address, :category, presence: true
  validates :category, inclusion: { in: ["Chinese", "Italian", "Japanese", "French", "Belgian"] }

  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, :content, presence: true
  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save!
      redirect_to restaurants_path
    else
      redirect_to restaurant_new_path
    end
  end

  def show
    @review = Review.new
    @restaurant = Restaurant.find(params[:id])
  end

  def index
    @restaurants = Restaurant.all
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    if @review.save!
      redirect_to restaurant_path(@restaurant)
    else
      redirect_to restaurants_path
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvpTa</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <!-- NAVBAR -->
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <%= link_to "#", class: "navbar-brand" do %>
        <%= image_tag "https://pic.onlinewebfonts.com/svg/img_174839.png" %>
      <% end %>
      <h1 style="text-align:center" class="title-navbar">Welcome !</h1>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto d-flex align-items-center">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://www.biography.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cg_face%2Cq_auto:good%2Cw_300/MTgwOTcxNDk2NDQzNzQ5NzM2/gettyimages-1148433914.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Add a restaurant",new_restaurant_path, class: "dropdown-item" %>
            </div>
          </li>
        </ul>
    </div>
    </div>
  <!-- PAGE CONTENT -->
    <%= yield %>
  <!--   FOOTER -->
    <!-- <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright">
        This footer is made with <i class="fas fa-heart"></i> at Le Wagon
      </div>
    </div> -->
  </body>
</html>

app/views/partials/_review.html.erb
        <div class="col review w-50 mb-10">
          <h5 style="text-align:center" class="mb-4">Add a review</h5>
          <%= simple_form_for [@restaurant, @review] do |f| %>
            <%= f.input :content %>
            <%= f.input :rating %>
            <%= f.submit 'Create it!', class: 'btn btn-primary' %>
          <% end %>
        </div>

app/views/restaurants/index.html.erb
<div class="container">
  <h2 style="text-align:center" class="mt-5">Discover our restaurants</h2>
  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-sm-4 d-flex align-items-stretch my-4">
        <div class="card" style="width: 22rem;">
          <%= image_tag "resto.jpg"%>
            <div class="card-body d-flex flex-column">
               <div class="card-header text-center mt-auto">
                <%= restaurant.category %>
               </div>
              <ul class="list-group list-group-flush mt-auto">
                <li class="list-group-item"><h5 class="text-primary mb-0 text-center"><strong><%= restaurant.name %></strong></h5></li>
                <li class="list-group-item">
                  <p class="mt-2 mb-4">
                    📍 <%= restaurant.address %> <br>
                    📞 <%= restaurant.phone_number %>
                  </p>
                </li>
              </ul>
              <div class="mt-auto">
              <%= link_to "Discover more", restaurant_path(restaurant), class: "btn btn-ghost" %>
              </div>
            </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container form-new">
  <div class="row justify-content-md-center">
    <h3 class="title-form">Add a restaurant</h3>
  </div>
  <div class="row justify-content-md-center">
    <div class="w-50">
        <%= simple_form_for @restaurant do |f| %>
            <%= f.input :name %>
            <%= f.input :category %>
            <%= f.input :address %>
            <%= f.input :phone_number %>
            <%= f.submit 'Create it!', class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container-show">
  <img src="https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1470&q=80" style="width:100%;">
  <!-- <div class="bottom-left">Bottom Left</div>
  <div class="top-left">Top Left</div>
  <div class="top-right">Top Right</div>
  <div class="bottom-right">Bottom Right</div> -->
  <div class="centered px-8">
      <div class="mt-4">
      <h2 style="text-align:center" class="col">Discover <%= @restaurant.name %> </h2>
      <h4 style="text-align:center" class="col mb-4"><em><%= @restaurant.category %> restaurant </em></h4>
      <p style="text-align:center" class="col mb-0"><%= @restaurant.address %></p>
      <p style="text-align:center" class="col"><%= @restaurant.phone_number %></p>
      <div class="row justify-content-md-center">
        <%= render 'partials/review' %>
       <div class="col review w-50 mb-10">
            <h5 style="text-align:center" class="mb-4">Reviews</h5>
            <% if @restaurant.reviews.count > 0 %>
              <% @restaurant.reviews.each do |review| %>
              <div style="text-align:left" class="px-3">
                <p> <%= review.content %> - <%= review.rating %> /5 ⭐</p>
                <p class="timestamp"><%= review.created_at %> </p>
              </div>
              <hr>
              <% end %>
            <% end %>
        </div>
      </div>

    </div>
  </div>
</div>